# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "MySageMath"
  config.vm.box_url = "http:www15191ue.sakura.ne.jp/pub/package.box"

  config.vm.network :forwarded_port, guest: 8888, host: 8888
  # config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true
    # Customize the amount of memory on the VM:
    vb.memory = "1536"
  end
end
