# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "SageMath7.2"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, guest: 8888, host: 8888
  # config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
  end
end
